name: Master
on:
  push:
    branches:
      - main
    workflow_dispatch:
      inputs:
        name: tag
        description: Tag to be created for the release
        type: string

defaults:
  run:
    shell: bash

jobs:
  production:
    runs-on: ubuntu-latest
    container:
      image: golang:1.17-buster
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: go build
        run: go build
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: azure-storage-azcopy
          asset_name: azcopy
          # we might create more than one PR that uses the same azcopy version
          tag: v10.16.1-aura-1
          overwrite: false
          body: "Forked Azcopy"
